---
- name: Initialize development environment
  hosts: localhost

  tasks:
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - fzf # TODO: Replace with building; add lazygit
          - git
          - luarocks
          - npm
          - pkg-config
          - python3-pip
          - python3-venv
          - software-properties-common
          - tmux
          - unzip
          - xsel
          - zip
        state: present

    - name: Pull git extensions
      ansible.builtin.git:
        repo: git@github.com:TheMikeste1/git-galaxy.git
        dest: ./git_commands
      tags:
        - update
    - name: Install TMUX Package Manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm
        clone: true
        update: true
        single_branch: true
    - name: Install TMUX plugins
      command: tmux source-file ~/.tmux.conf

- name: Setup CMake
  ansible.builtin.import_playbook: playbooks/cmake.yaml
  tags:
    - cmake

- name: Setup ninja-build
  ansible.builtin.import_playbook: playbooks/ninja.yaml
  tags:
    - ninja

- name: Setup mold linker
  ansible.builtin.import_playbook: playbooks/mold.yaml
  tags:
    - mold

- name: Setup Rust
  ansible.builtin.import_playbook: playbooks/rust.yaml
  tags:
    - rust


- name: Setup NeoVim
  ansible.builtin.import_playbook: playbooks/neovim.yaml
  tags:
    - neovim

- name: Setup Zsh
  ansible.builtin.import_playbook: playbooks/zsh.yaml
  tags:
    - zsh

- name: Setup Fish
  when: false
  ansible.builtin.import_playbook: playbooks/fish.yaml
  tags:
    - fish
