---
- name: Initialize development environment
  hosts: localhost

  tasks:
    - name: Install packages with apt
      become: true
      ansible.builtin.apt:
        name:
          - build-essential
          - git
          - luarocks
          - npm
          - pinentry-qt
          - pkg-config
          - python3-pip
          - python3-venv
          - software-properties-common
          - tmux
          - unzip
          - xsel
          - zip
        state: present

    - name: Pull git extensions
      ansible.builtin.git:
        repo: git@github.com:TheMikeste1/git-galaxy.git
        dest: ./git_commands

    - name: Install TMUX Package Manager
      ansible.builtin.git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm
        clone: true
        update: true
        single_branch: true
    - name: Install TMUX plugins
      command: tmux source-file ~/.tmux.conf

- name: Setup CMake
  ansible.builtin.import_playbook: playbooks/cmake.yaml

- name: Setup ninja-build
  ansible.builtin.import_playbook: playbooks/ninja.yaml

- name: Setup mold linker
  ansible.builtin.import_playbook: playbooks/mold.yaml

- name: Setup Go
  ansible.builtin.import_playbook: playbooks/go.yaml

- name: Setup Rust
  ansible.builtin.import_playbook: playbooks/rust.yaml

- name: Setup NeoVim
  ansible.builtin.import_playbook: playbooks/neovim.yaml

- name: Setup Mise
  ansible.builtin.import_playbook: playbooks/mise.yaml

- name: Setup Zsh
  ansible.builtin.import_playbook: playbooks/zsh.yaml

- name: Setup Fish
  when: false
  ansible.builtin.import_playbook: playbooks/fish.yaml
