#!/usr/bin/env bash

readonly EVAL_CACHE_DIR="$HOME/.cache/eval"
if [[ ! -d "$EVAL_CACHE_DIR" ]]; then
    mkdir -p "$EVAL_CACHE_DIR"
fi

# Initialize where the dotfiles are
export DOTFILES="$HOME/.local/share/chezmoi"

export EDITOR=nvim

# Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# CMake
export CMAKE_EXPORT_COMPILE_COMMANDS=ON

# C# tools
export PATH="$PATH:$HOME/.dotnet/tools"

# Docker
export COMPOSE_BAKE=true

# Custom git commands
export PATH="$PATH:$DOTFILES/git_commands"

# Go
export PATH="$PATH:/usr/local/go/bin"
export GOBIN="$HOME/.local/go/bin"

# Ninja by default
export CMAKE_GENERATOR=Ninja
export NINJA_STATUS="[%p (%f/%t) :: (%e|%E)] "
export CMAKE_COLOR_DIAGNOSTICS=ON

# Python packages
export PATH="$HOME/.local/bin:$PATH"

# SSH
export SSH_ENV="$HOME/.ssh/agent-environment"
export SSH_ASKPASS="/usr/lib/openssh/gnome-ssh-askpass"
export SSH_ASKPASS_REQUIRE=prefer

# `less` config
# https://www.topbug.net/blog/2016/09/27/make-gnu-less-more-powerful/
export LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4'

export XDG_CONFIG_HOME="$HOME/.config"

# Get access to NVim Mason executables
export PATH="$PATH:$HOME/.local/share/nvim/mason/bin"

# No telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT="true"

# WSL
if uname -r | grep -q "WSL"; then
    # Use WSLu for browser integration
    export BROWSER=wslview

    declare -xr ON_WSL=true
    export PATH="$PATH:/mnt/c/Windows/System32"
    export PATH="$PATH:/mnt/c/Windows/System32/WindowsPowerShell/v1.0"

    if [[ ! -f "$EVAL_CACHE_DIR/wsl_constants.bash" ]]; then
        echo "Performing WSL first time setup. . ."

        echo "declare -xr WINDOWS_USERNAME=\"$(powershell.exe -Command 'echo $env:USERNAME' | tr -d '\r')\"
        export PATH=\"\$PATH:/mnt/c/users/\$WINDOWS_USERNAME/AppData/Local/Programs/Microsoft VS Code/bin\"" \
        > "$EVAL_CACHE_DIR/wsl_constants.bash"
    fi

    source "$EVAL_CACHE_DIR/wsl_constants.bash"
fi


# Machine-specific env and overrides
source "$HOME/.local.bash_env" 2>/dev/null
