#!/usr/bin/env bash

# Initialize where the dotfiles are
export DOTFILES="$HOME/.local/share/chezmoi"

# My command line utilities
export PATH="$HOME/bin:$PATH"

export EDITOR=nvim

# Cargo
export PATH="$HOME/.cargo/bin:$PATH"

# CMake
export CMAKE_EXPORT_COMPILE_COMMANDS=ON

# C# tools
export PATH="$PATH:$HOME/.dotnet/tools"

# Docker
export COMPOSE_BAKE=true

# Custom git commands
export PATH="$PATH:$DOTFILES/git_commands"

# Go
export GOBIN="$HOME/.local/go/bin"
export PATH="$PATH:/usr/local/go/bin:$GOBIN"

# Ninja by default
export CMAKE_GENERATOR=Ninja
export NINJA_STATUS="[%p (%f/%t) :: (%e|%E)] "
export CMAKE_COLOR_DIAGNOSTICS=ON

# SSH
export SSH_ENV="$HOME/.ssh/agent-environment"
export SSH_ASKPASS="/usr/lib/openssh/gnome-ssh-askpass"
export SSH_ASKPASS_REQUIRE=prefer

# Lua
export PATH="$PATH:$HOME/.luarocks/bin"

# `less` config
# https://www.topbug.net/blog/2016/09/27/make-gnu-less-more-powerful/
export LESS='--quit-if-one-screen --ignore-case --status-column --LONG-PROMPT --RAW-CONTROL-CHARS --HILITE-UNREAD --tabs=4 --no-init --window=-4'

export XDG_CONFIG_HOME="$HOME/.config"

# Get access to NVim Mason executables
export PATH="$PATH:$HOME/.local/share/nvim/mason/bin"

# No telemetry
export DOTNET_CLI_TELEMETRY_OPTOUT="true"

# WSL
if uname -r | grep -q "WSL"; then
    declare -xr ON_WSL=true
    export PATH="$PATH:/mnt/c/Windows/System32/WindowsPowerShell/v1.0"
    export PATH="$PATH:/mnt/c/Program Files/Git/cmd"
    export PATH="$PATH:/mnt/c/Windows/System32"

    if [[ ! -f "$EVAL_CACHE_DIR/wsl_constants.bash" ]]; then
        echo "Performing WSL first time setup. . ."
        WINDOWS_USERNAME="$(powershell.exe -Command 'echo $env:USERNAME' | tr -d '\r')"
        WINDOWS_HOMEDIR="$(wslpath -u "$(powershell.exe -Command 'echo $env:USERPROFILE')" | tr -d '\r')"
        VSCODE_PATH="$WINDOWS_HOMEDIR/AppData/Local/Programs/Microsoft VS Code/bin"
        FIREFOX_PATH="$WINDOWS_HOMEDIR/AppData/Local/Mozilla Firefox"
        if [[ ! -f "$FIREFOX_PATH/firefox.exe" ]]; then
            FIREFOX_PATH="/mnt/c/Program Files/Mozilla Firefox"
        fi


        # shellcheck disable=SC2016
        echo "declare -xr WINDOWS_USERNAME=\"$WINDOWS_USERNAME\"
declare -xr WINDOWS_HOMEDIR=\"$WINDOWS_HOMEDIR\"
declare -xr FIREFOX_PATH=\"$FIREFOX_PATH\"
declare -xr VSCODE_PATH=\"$VSCODE_PATH\"
" > "$EVAL_CACHE_DIR/wsl_constants.bash"
    fi

    source "$EVAL_CACHE_DIR/wsl_constants.bash"

    export PATH="$PATH:$VSCODE_PATH"
    export PATH="$PATH:$FIREFOX_PATH"
    export BROWSER=firefox.exe
fi

export PATH="${PATH%:"${HOME}"/.vscode-server/bin/*/bin/remote-cli}"

# Machine-specific env and overrides
source "$HOME/.local.bash_env" 2>/dev/null
