#!/usr/bin/env bash

alias explorer.exe=/mnt/c/windows/explorer.exe

# Because I never use Python 2
alias python=python3

alias batcat=bat
alias cat=batcat

alias ls='eza --icons -F -H --group-directories-first --git'
