#!/usr/bin/env zsh

# TMUX autoconnect
if [[ "$TMUX" = "" ]]; then
  # Automatically connect to the session
  sessions=("$(tmux ls -F "#{session_name}:#{session_attached}" 2> /dev/null)")
  for session in "${sessions[@]}";
  do
    parts=("${(s/:/)session}")
    if [[ "${parts[1]}" = "default" ]]; then
      default_session_state=${parts[2]}
      break
    fi
  done

  if [[ "$default_session_state" = "" ]]; # Session does not exist
  then
    exec tmux new -s default >/dev/null
  elif [[ "$default_session_state" = 0 ]]; # Session exists but is not attached
  then
    exec tmux attach -t default
  fi
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

# Set PATH so it includes user's private bin if it exists
if [ -d "$HOME/.local/bin" ] ; then
    PATH="$HOME/.local/bin:$PATH"
fi

# https://stackoverflow.com/a/18915067
function ssh-activate() {
  function __start_agent {
    ssh-agent | sed 's/^SSH/export SSH/' | sed 's/^echo/#echo/' >"$SSH_ENV"
    chmod 600 "$SSH_ENV"
    # shellcheck source=/dev/null
    . "$SSH_ENV" >/dev/null
  }

  if [ -f "$SSH_ENV" ]; then
    # shellcheck source=/dev/null
    . "$SSH_ENV" >/dev/null
    ps -ef | grep "$SSH_AGENT_PID" | grep ssh-agent$ >/dev/null || {
      __start_agent
    }
  else
    __start_agent
  fi
}

# Start SSH agent on launch
ssh-activate
