---
- name: Check if {{ package.name }} is installed
  shell: command -v {{ package.bin | default(package.name) }}
  register: tool_installed
  ignore_errors: true
  changed_when: false
- name: Install {{ package.name }}
  when: tool_installed.rc != 0
  command:
    cmd: cargo install --git {{ package.url }} {{ package.name }}
