[window]

[scrolling]
history = 0 # Disable history

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
size = 10

[selection]
save_to_clipboard = true

[terminal]
# The program could also be "Ubuntu", but this uses the default distro
shell = { program = "wsl", args = ["--cd ~"] }
