If:
  PathExclude:
    - .*/build/.*
    - .*/\.cache/.*

CompileFlags:
  Add:
    - -Wall
    - -Wextra
    - -Wpedantic
    - -Wconversion
    - -Wsign-conversion

Index:
  Background: Build

Completion:
  AllScopes: true
  HeaderInsertion: IWYU

Diagnostics:
  UnusedIncludes: Strict
  MissingIncludes: Strict

  ClangTidy:
    FastCheckFilter: None

    Add:
      - bugprone-*
      - cert-*
      - cppcoreguidelines-*
      - misc-*
      - misc-const-correctness
      - modernize-*
      - performance-*
      - portability-*
      - readability-*

    Remove:
      # Too noisy
      - readability-magic-numbers
      - cppcoreguidelines-avoid-magic-numbers

      - modernize-use-trailing-return-type

Hover:
  ShowAKA: true

InlayHints:
  Enabled: true

  BlockEnd: true
  Designators: true
  DefaultArguments: true
  ParameterNames: true
  DeducedTypes: true

Documentation:
  CommentFormat: Doxygen
