---
- name: Ensure package managers are installed
  include_tasks: install_package.yml
  loop: '{{ managed_packages }}'
  loop_control:
    label: '{{ item.name }}'
  vars:
    package: '{{ item }}'
- name: Ensure OhMyPosh is installed
  block:
    - name: Check whether OhMyPosh is installed and on system path
      command: which oh-my-posh
      check_mode: false
      changed_when: false
      register: omp_installed
      ignore_errors: true
    - name: Install OhMyPosh
      when: omp_installed.rc != 0
      block:
        - name: Download OhMyPosh installer
          get_url:
            url: https://ohmyposh.dev/install.sh
            dest: /tmp/ohmyposh-install.sh
            mode: '0755'
            force: true
        - name: Install oh-my-posh
          shell: /tmp/ohmyposh-install.sh
- name: Install TMUX Package Manager
  git:
    repo: https://github.com/tmux-plugins/tpm.git
    dest: ~/.tmux/plugins/tpm
    clone: true
    update: true
    single_branch: true
