#!/usr/bin/env bash
set -euo pipefail

usage() {
  echo "Usage:  [OPTIONS]"
  echo '  -h, --help         Display this help message'
  echo '  --local            Generate the key for the current config'\''s email'
  echo '  --global           Generate the key for the global config'\''s email'
  exit 1
}

# Rely on git's default config resolution
global=
while [[ $# -gt 0 ]]; do
  case "$1" in
    --local)
      global="--local"
      ;;
    --global)
      global="--global"
      ;;
    *)
      echo "Error: Unknown option $1" >&2
      usage
      ;;
  esac
done
readonly global

git_email="$(git config $global user.email)" || { echo "Please configure your git email" >&2; exit 1; }
readonly git_email
git_name="$(git config $global user.name)" || { echo "Please configure your git name" >&2; exit 1; }
readonly git_name

public_key_id="$(gpg --quick-generate-key "${git_name} <$git_email>" | tee /dev/stderr | grep  -A 1 "pub")"
mapfile -t lines <<<"$public_key_id"

if [[ ${#lines[@]} != 2 ]]; then
  echo "Failed to extract public key!" >&2
  echo "Manually copy the key ID."
  read -r public_key_id
else
  public_key_id="${lines[1]}"
fi

shopt -s extglob
public_key_id="${public_key_id##+([[:space:]])}"
public_key_id="${public_key_id%%+([[:space:]])}"
shopt -u extglob
readonly public_key_id

echo "Got public key $public_key_id"
key_contents="$(gpg --armor --export "$public_key_id")"
readonly key_contents

if grep -qE "(Microsoft|Microsoft-Standard-WSL2)" /proc/version 2> /dev/null; then
  clip.exe <<<"$key_contents"
elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  wl-copy <<<"$key_contents"
elif command -v xclip 2>/dev/null; then
  xclip -sel clip <<<"$key_contents"
elif command -v xsel 2>/dev/null; then
  xsel -ib <<<"$key_contents"
else
  echo "Cannot determine clipboard. Copy the following manually:"
  printf '%s\n' "$key_contents"
  wait
fi

echo "Public key copied to clipboard."
git config $global user.signingkey "$public_key_id"
echo "Git config set to use $public_key_id as signing key"

domain="$(git remote get-url origin 2>/dev/null | sed -E 's/.*@|https?:\/\/([^/:]+).*/\1/;s/:.*//')" || {
  echo "No git domain found for $PWD. Go add your key to the desired repositories."
  exit 0
}
readonly domain
echo "Navigating to https://$domain. Paste the copied public key into the appropriate fields."
sleep 0.1
case "$domain" in
  "github"*)
    xdg-open "https://$domain/settings/gpg/new"
    ;;
  "bitbucket"*)
    xdg-open "https://$domain/plugins/servlet/gpg/account/keys/add"
    ;;
esac
