---
- name: Check for Go
  hosts: localhost
  tasks:
    - name: Check whether Go is installed and on system path
      command: which go
      check_mode: false
      changed_when: false
      failed_when: go_installed.rc > 0
      register: go_installed
      ignore_errors: true
- name: Build Go
  ansible.builtin.import_playbook: build/go.yaml
  when: go_installed.failed
- name: Verify Go installation
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get Go version
      ansible.builtin.command: go version
      register: go_version_output
      changed_when: false
    - name: Display Go version
      ansible.builtin.debug:
        var: go_version_output.stdout
- name: Install Go packages
  hosts: localhost
  tasks:
    - name: Install a specific Go package
      ansible.builtin.command: >
        go install {{ item.key }}@{{ item.value }}
      with_dict:
        github.com/evilmartians/lefthook: "v1.12.2"
        github.com/junegunn/fzf: "v0.65.1"
      loop_control:
        label: "{{ item.key }}"
