---
- name: Initialize ZSH
  hosts: localhost

  tasks:
    - name: Install Zsh
      become: true
      ansible.builtin.apt:
        name:
          - zsh
        state: present
    - name: Set Zsh as default shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: Check whether oh-my-posh is installed and on system path
      command: "which oh-my-posh"
      check_mode: false
      changed_when: false
      failed_when: omp_installed.rc > 0
      register: omp_installed
      ignore_errors: true
    - name: Download OhMyPosh installer
      when: omp_installed.failed
      get_url:
        url: https://ohmyposh.dev/install.sh
        dest: /tmp/ohmyposh-install.sh
        mode: "0755"
        force: true
    - name: Install oh-my-posh
      when: omp_installed.failed
      shell: /tmp/ohmyposh-install.sh

